services:
  # The FastAPI Backend + Background ML Pipeline
  - type: web
    name: surf-health-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: us-west
    plan: free
    envVars:
      - key: APP_ENV
        value: production
