import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background pt-32 pb-24">
      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-4">
          <Link href="/" className="font-mono text-[11px] text-muted-foreground hover:text-foreground transition-colors tracking-widest">
            ← Home
          </Link>
        </div>

        <div className="text-primary text-sm tracking-widest uppercase font-medium mb-4">
          Legal
        </div>
        <h1 className="text-5xl md:text-7xl font-light mb-8 text-foreground text-balance">
          Terms of Service
        </h1>
        
        <p className="text-xl text-muted-foreground leading-relaxed max-w-3xl mb-16">
          Effective Date: April 28, 2026. Please read these Terms of Service 
          carefully before using the Shorelife website and mobile application.
        </p>

        <div className="space-y-16 mt-16 border-t border-border/50 pt-16">
          <section>
            <h2 className="text-3xl font-light mb-6 text-foreground">
              1. Informational Purposes Only
            </h2>
            <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
              Shorelife provides probabilistic forecasts of coastal water quality and surf conditions. 
              These forecasts are generated by machine learning models and are <strong>not actual water samples or certified results</strong>. 
              They are intended for informational purposes only. A "Low" risk band does not guarantee safe water, 
              and localized events such as sewage spills or storm runoff can override model predictions. 
              For confirmed regulatory status, you must consult the current county health advisory for the specific beach.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-light mb-6 text-foreground">
              2. Disclaimer of Warranties
            </h2>
            <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
              The services and information provided by Shorelife are provided on an "AS IS" and "AS AVAILABLE" basis. 
              We make no warranties, express or implied, regarding the accuracy, completeness, reliability, or suitability 
              of the forecasts or data provided.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-light mb-6 text-foreground">
              3. Limitation of Liability
            </h2>
            <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
              To the maximum extent permitted by applicable law, Shorelife and its creators shall not be liable for any 
              direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to 
              health-related issues, illness, or injury, resulting from your access to or use of, or inability to access 
              or use, the Shorelife services or any information provided therein. You agree to use the service at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-light mb-6 text-foreground">
              4. Open Source and Licensing
            </h2>
            <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
              Certain components of the Shorelife project may be open-sourced and provided under their respective licenses 
              (e.g., MIT License). Your use of those source code components is governed by the applicable open-source license.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-light mb-6 text-foreground">
              5. Contact
            </h2>
            <p className="text-base text-muted-foreground leading-relaxed max-w-2xl">
              If you have any questions about these Terms, please contact us at{' '}
              <a href="mailto:kylechoidsc@gmail.com" className="text-primary hover:underline font-medium">kylechoidsc@gmail.com</a>.
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}