import React from 'react';
import Link from 'next/link';
import { EditorialPage } from '@/components/EditorialPage';

export default function TermsPage() {
  return (
    <EditorialPage>
      <article style={{ padding: '64px 64px 96px', maxWidth: 1280, margin: '0 auto' }}>
        <div style={{ marginBottom: 12 }}>
          <Link href="/" style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--sl-muted)', textDecoration: 'none', letterSpacing: '0.08em' }}>
            ← Home
          </Link>
        </div>

        <div style={{ color: 'var(--sl-sun-deep)', fontFamily: 'var(--font-mono)', fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.12em' }}>
          Legal
        </div>
        <h1 style={{ fontFamily: 'var(--font-heading)', fontSize: 80, marginTop: 18, marginBottom: 32, fontWeight: 400, letterSpacing: '-0.02em', color: 'var(--sl-navy-ink)', maxWidth: 900, lineHeight: 1.1 }}>
          Terms of Service
        </h1>
        
        <p style={{ fontFamily: 'var(--font-text)', fontSize: 20, color: 'var(--sl-ink)', lineHeight: 1.6, maxWidth: 680, margin: '0 0 40px' }}>
          Effective Date: April 28, 2026. Please read these Terms of Service 
          carefully before using the Shorelife website and mobile application.
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 40, marginTop: 40, borderTop: '1px solid var(--sl-line)', paddingTop: 40 }}>
          <section>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: 28, color: 'var(--sl-navy)', marginBottom: 16, fontWeight: 400 }}>
              1. Informational Purposes Only
            </h2>
            <p style={{ fontFamily: 'var(--font-text)', fontSize: 16, color: 'var(--sl-ink)', lineHeight: 1.65, maxWidth: 680, margin: 0 }}>
              Shorelife provides probabilistic forecasts of coastal water quality and surf conditions. 
              These forecasts are generated by machine learning models and are <strong>not actual water samples or certified results</strong>. 
              They are intended for informational purposes only. A "Low" risk band does not guarantee safe water, 
              and localized events such as sewage spills or storm runoff can override model predictions. 
              For confirmed regulatory status, you must consult the current county health advisory for the specific beach.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: 28, color: 'var(--sl-navy)', marginBottom: 16, fontWeight: 400 }}>
              2. Disclaimer of Warranties
            </h2>
            <p style={{ fontFamily: 'var(--font-text)', fontSize: 16, color: 'var(--sl-ink)', lineHeight: 1.65, maxWidth: 680, margin: 0 }}>
              The services and information provided by Shorelife are provided on an "AS IS" and "AS AVAILABLE" basis. 
              We make no warranties, express or implied, regarding the accuracy, completeness, reliability, or suitability 
              of the forecasts or data provided.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: 28, color: 'var(--sl-navy)', marginBottom: 16, fontWeight: 400 }}>
              3. Limitation of Liability
            </h2>
            <p style={{ fontFamily: 'var(--font-text)', fontSize: 16, color: 'var(--sl-ink)', lineHeight: 1.65, maxWidth: 680, margin: 0 }}>
              To the maximum extent permitted by applicable law, Shorelife and its creators shall not be liable for any 
              direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to 
              health-related issues, illness, or injury, resulting from your access to or use of, or inability to access 
              or use, the Shorelife services or any information provided therein. You agree to use the service at your own risk.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: 28, color: 'var(--sl-navy)', marginBottom: 16, fontWeight: 400 }}>
              4. Open Source and Licensing
            </h2>
            <p style={{ fontFamily: 'var(--font-text)', fontSize: 16, color: 'var(--sl-ink)', lineHeight: 1.65, maxWidth: 680, margin: 0 }}>
              Certain components of the Shorelife project may be open-sourced and provided under their respective licenses 
              (e.g., MIT License). Your use of those source code components is governed by the applicable open-source license.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: 28, color: 'var(--sl-navy)', marginBottom: 16, fontWeight: 400 }}>
              5. Contact
            </h2>
            <p style={{ fontFamily: 'var(--font-text)', fontSize: 16, color: 'var(--sl-ink)', lineHeight: 1.65, maxWidth: 680, margin: 0 }}>
              If you have any questions about these Terms, please contact us at 
              <a href="mailto:kylechoidsc@gmail.com" style={{ color: 'var(--sl-navy)', textDecoration: 'underline', marginLeft: 6 }}>kylechoidsc@gmail.com</a>.
            </p>
          </section>
        </div>
      </article>
    </EditorialPage>
  );
}