"""Fetch a Google Street View photo for every parent beach and bundle them
into the mobile app's static assets.

Usage:
    GOOGLE_MAPS_KEY=... python scripts/fetch_beach_photos.py

Writes:
    mobile/assets/beach-photos/<beach_id>.jpg     for beaches with coverage
    mobile/lib/bundledBeachPhotos.ts              static require() manifest

For beaches without Street View coverage, the manifest entry is omitted and
the existing curated Unsplash pool serves as the runtime fallback.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from urllib.parse import urlencode

import httpx

REPO = Path(__file__).resolve().parent.parent
API_URL = os.environ.get("API_URL", "https://surf-health-api.onrender.com")
KEY = os.environ.get("GOOGLE_MAPS_KEY")
PHOTOS_DIR = REPO / "mobile" / "assets" / "beach-photos"
MANIFEST_PATH = REPO / "mobile" / "lib" / "bundledBeachPhotos.ts"

IMG_W, IMG_H = 400, 267
SEARCH_RADIUS = 1000  # meters — beaches rarely have panoramas at the water itself


def metadata_status(client: httpx.Client, lat: float, lon: float) -> str:
    params = {
        "location": f"{lat},{lon}",
        "radius": SEARCH_RADIUS,
        "source": "outdoor",
        "key": KEY,
    }
    r = client.get(f"https://maps.googleapis.com/maps/api/streetview/metadata?{urlencode(params)}")
    return r.json().get("status", "UNKNOWN")


def download_image(client: httpx.Client, lat: float, lon: float, dest: Path) -> bool:
    params = {
        "size": f"{IMG_W}x{IMG_H}",
        "location": f"{lat},{lon}",
        "radius": SEARCH_RADIUS,
        "source": "outdoor",
        "fov": 90,
        "pitch": 5,
        "key": KEY,
    }
    r = client.get(f"https://maps.googleapis.com/maps/api/streetview?{urlencode(params)}")
    if r.status_code != 200 or len(r.content) < 1000:
        return False
    dest.write_bytes(r.content)
    return True


def main() -> int:
    if not KEY:
        print("Set GOOGLE_MAPS_KEY env var", file=sys.stderr)
        return 1

    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    with httpx.Client(timeout=30) as client:
        beaches = client.get(f"{API_URL}/parent-beaches").json()
        print(f"Fetched {len(beaches)} parent beaches from {API_URL}")

        covered: list[str] = []
        skipped: list[str] = []

        for i, b in enumerate(beaches, 1):
            bid = b["id"]
            lat = b["geometry"]["latitude"]
            lon = b["geometry"]["longitude"]
            status = metadata_status(client, lat, lon)
            if status != "OK":
                skipped.append(bid)
                print(f"[{i}/{len(beaches)}] SKIP {bid} ({status})")
                continue
            dest = PHOTOS_DIR / f"{bid}.jpg"
            if download_image(client, lat, lon, dest):
                covered.append(bid)
                print(f"[{i}/{len(beaches)}] OK   {bid}  ({dest.stat().st_size // 1024}KB)")
            else:
                skipped.append(bid)
                print(f"[{i}/{len(beaches)}] FAIL {bid}")
            if i % 50 == 0:
                time.sleep(1)  # gentle rate-limit

    lines = ["// Auto-generated by scripts/fetch_beach_photos.py. Do not edit."]
    lines.append("// Each entry is a static require() so Metro bundles the asset.")
    lines.append("export const BUNDLED_BEACH_PHOTOS: Record<string, number> = {")
    for bid in sorted(covered):
        lines.append(f'  "{bid}": require("../assets/beach-photos/{bid}.jpg"),')
    lines.append("};")
    MANIFEST_PATH.write_text("\n".join(lines) + "\n")

    print(f"\nDone. Covered: {len(covered)}  Skipped: {len(skipped)}")
    print(f"Manifest: {MANIFEST_PATH}")
    print(f"Approx bundle size: {sum((PHOTOS_DIR / f'{b}.jpg').stat().st_size for b in covered) // (1024*1024)}MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
