"""Fetch a Surfline cam still for every California beach we can match.

Designed to run during daylight hours (14:00 PST is a good target — sun is
high and afternoon onshore breeze gives the cleanest visibility for most
California beaches).

Steps:
1. Pull every Surfline spot inside the California bounding box from the
   public mapview API (no auth required).
2. For each parent beach in our API, find the closest Surfline spot with
   a public cam (great-circle distance, cap at 5km).
3. Download `cameras[0].stillUrl` for matched spots and save into
   `mobile/assets/beach-photos-cams/`.
4. Regenerate `mobile/lib/bundledBeachPhotos.ts` to include the cam stills.

Usage:
    python scripts/fetch_surfline_cams.py
"""
from __future__ import annotations

import json
import math
import os
import sys
import time
from pathlib import Path

import httpx

REPO = Path(__file__).resolve().parent.parent
API_URL = os.environ.get("API_URL", "https://surf-health-api-aabr.onrender.com")
PHOTOS_DIR = REPO / "mobile" / "assets" / "beach-photos-cams"
MANIFEST_PATH = REPO / "mobile" / "lib" / "bundledBeachPhotos.ts"

# California bounding box, slightly inflated. Surfline mapview limits a single
# call to a tile, so we sweep down the coast in 1-degree latitude bands.
LAT_BANDS = [(33.0, 34.0), (34.0, 35.0), (35.0, 36.0), (36.0, 37.0),
             (37.0, 38.0), (38.0, 39.0), (39.0, 40.0), (40.0, 41.0),
             (41.0, 42.0)]
LON_W, LON_E = -125.0, -117.0

MAX_MATCH_KM = 5.0


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0
    p = math.pi / 180
    a = (0.5 - math.cos((lat2 - lat1) * p) / 2
         + math.cos(lat1 * p) * math.cos(lat2 * p) * (1 - math.cos((lon2 - lon1) * p)) / 2)
    return 2 * r * math.asin(math.sqrt(a))


def fetch_surfline_spots(client: httpx.Client) -> list[dict]:
    spots: dict[str, dict] = {}
    for s, n in LAT_BANDS:
        r = client.get("https://services.surfline.com/kbyg/mapview", params={
            "north": n, "south": s, "east": LON_E, "west": LON_W,
        })
        if r.status_code != 200:
            continue
        for spot in r.json().get("data", {}).get("spots", []):
            cams = spot.get("cameras") or []
            still = cams[0].get("stillUrl") if cams else None
            if not still:
                continue
            spots[spot["_id"]] = {
                "id": spot["_id"],
                "name": spot.get("name"),
                "lat": spot.get("lat"),
                "lon": spot.get("lon"),
                "stillUrl": still,
            }
        time.sleep(0.5)  # gentle on Surfline
    return list(spots.values())


def main() -> int:
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    with httpx.Client(timeout=30) as client:
        print("Pulling California Surfline spots…")
        spots = fetch_surfline_spots(client)
        print(f"  found {len(spots)} spots with public cams")

        beaches = client.get(f"{API_URL}/parent-beaches").json()
        print(f"Matching {len(beaches)} parent beaches to nearest cam…")

        covered: dict[str, str] = {}
        skipped: int = 0

        for i, b in enumerate(beaches, 1):
            bid = b["id"]
            blat = b["geometry"]["latitude"]
            blon = b["geometry"]["longitude"]

            best = None
            best_d = MAX_MATCH_KM
            for s in spots:
                if s["lat"] is None or s["lon"] is None:
                    continue
                d = haversine_km(blat, blon, s["lat"], s["lon"])
                if d < best_d:
                    best_d = d
                    best = s

            if not best:
                skipped += 1
                continue

            r = client.get(best["stillUrl"])
            if r.status_code != 200 or len(r.content) < 1000:
                skipped += 1
                continue

            dest = PHOTOS_DIR / f"{bid}.jpg"
            dest.write_bytes(r.content)
            covered[bid] = best["name"]
            print(f"[{i}/{len(beaches)}] OK  {bid}  ← {best['name']}  ({best_d:.1f}km, {dest.stat().st_size // 1024}KB)")

        lines = ["// Auto-generated by scripts/fetch_surfline_cams.py. Do not edit."]
        lines.append("// Each entry is a static require() so Metro bundles the asset.")
        lines.append("export const BUNDLED_BEACH_PHOTOS: Record<string, number> = {")
        for bid in sorted(covered):
            lines.append(f'  "{bid}": require("../assets/beach-photos-cams/{bid}.jpg"),')
        lines.append("};")
        MANIFEST_PATH.write_text("\n".join(lines) + "\n")

        total_bytes = sum((PHOTOS_DIR / f"{b}.jpg").stat().st_size for b in covered)
        print(f"\nDone. Cam stills: {len(covered)}  Skipped: {skipped}")
        print(f"Bundle size: {total_bytes // (1024*1024)}MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
